apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nocountryc1210.azurecr.io/frontend:52b05c045d2c86c8cd9fe5cdf2f72f2e2496568d
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: demo-k8s-secret