apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nocountryc1210.azurecr.io/frontend:latest
        ports:
          - containerPort: 80
        volumeMounts:
        - name: angular-config-volume
          mountPath: /src/environments/

        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf/
      imagePullSecrets:
      - name: demo-k8s-secret

      volumes:
        - name: angular-config-volume
          configMap:
            name: angular-cm
            items:
            - key: environment.ts
              path: environment.ts

        - name: nginx-config-volume
          configMap:
            name: nginx-cm
            items:
            - key: nginx.conf
              path: nginx.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-cm
data:
  environment.ts: |
    export const environment = {
      production: false,
      apiUrl: 'backend-service.default.svc.cluster.local:8082',
      enableDebugMode: true,
      // Add other environment-specific configuration here
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include mime.types;
        default_type application/octet-stream;
        sendfile on;

        gzip on;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;

        server {
            listen 80;

            # Replace 'your-angular-app-domain.com' with your actual domain name
            # server_name 4.157.80.23;

            location / {
                # Replace '/path/to/angular/dist' with the path to your Angular app's built files
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
        }
    }
