name: Build and deploy to Azure Kubernetes Service

env:
  AZURE_CONTAINER_REGISTRY: MY_REGISTRY_NAME # set this to the name of your container registry
  PROJECT_NAME: MY_PROJECT_NAME              # set this to your project's name
  RESOURCE_GROUP: nocountry          # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: nocountryc1210              # set this to the name of your AKS cluster
  REGISTRY_URL: nocountryc1210.azurecr.io             # set this to the URL of your registry
  # # If you bake using helm:
  # CHART_PATH: MY_HELM_FILE                   # set this to the path to your helm file
  # CHART_OVERRIDE_PATH: MY_OVERRIDE_FILES     # set this to an array of override file paths

on:
  push:
    branches:
      - develop-dockerfiles

jobs:
  login-get-k8s-context:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Azure/docker-login@v1
      with:
       login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
       username: ${{ secrets.AZURE_LOGIN }}
       password: ${{ secrets.AZURE_PASSWORD }}

    - name: Azure Login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # enable-AzPSSession: true
        # allow-no-subscriptions: true
    - uses: azure/setup-kubectl@v2.0
    - name: Gets K8s context
      uses: azure/aks-set-context@v3
      with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
    - uses:  azure/k8s-create-secret@v4
      with:
              container-registry-url: nocountryc1210.azurecr.io
              container-registry-username: ${{ secrets.AZURE_LOGIN }}
              container-registry-password: ${{ secrets.AZURE_PASSWORD }}
              secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v4
      with:
              action: deploy
              manifests: |
                 manifests/deployment.yml
                 manifests/service.yml
              images: |
                 nocountryc1210.azurecr.io/frontend
              imagepullsecrets: |
                 demo-k8s-secret

    
 






        # jobs:
#   deploy-to-AKS:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Login to Azure
#       uses: azure/login@v1
#       with:
#        client-id: ${{ secrets.AZURE_CLIENT_ID }}
#        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#     - uses: azure/aks-set-context@v3
#       with:
#         resource-group: 'nocountry'
#         cluster-name: 'nocountry1210'









    #    Name               Id                                   TenantId                             State
    #    ----               --                                   --------                             -----
    #    Azure for Students 15bbf234-7bb4-41f0-ab67-15a4b3d9c66f 4ae54b05-b77e-4224-aef1-8661422e0816 Enabled




#   az ad sp create-for-rbac --name "mykubeapp" --role contributor --scopes /subscriptions/15bbf234-7bb4-41f0-ab67-15a4b3d9c66f/resourceGroups/nocountry --sdk-auth

# {
#   "clientId": "76a24d18-fb2e-4532-b4d5-95911dbc88b2",
#   "clientSecret": "2RJ8Q~w_Z56DL9RjIPOsr8HWkSV3WBspVNgVgbGE",
#   "subscriptionId": "15bbf234-7bb4-41f0-ab67-15a4b3d9c66f",
#   "tenantId": "4ae54b05-b77e-4224-aef1-8661422e0816",
#   "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
#   "resourceManagerEndpointUrl": "https://management.azure.com/",
#   "activeDirectoryGraphResourceId": "https://graph.windows.net/",
#   "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
#   "galleryEndpointUrl": "https://gallery.azure.com/",
#   "managementEndpointUrl": "https://management.core.windows.net/"
# }

  